project:
  type: website
  output-dir: docs

# Meta
description-meta: "Website Mehul"
author-meta: "Dr. Mehulkumar Shiroya"

website:
  title: "Mehulkumar Shiroya"
  image: ""
  description: ""

  navbar:
    background: light

    left:
      - text: About
        menu:
          - text: Contact
            href: contact.qmd

      - text: Research
        menu:
          - text: List of Publications
            href: publications.qmd
          - text: Selected Papers
            href: posts.qmd#category=paper

      - text: Certificates
        menu:
          - text: Academic
            href: academic.qmd
          - text: Professional
            href: professional.qmd

    right:
      - text: CV
        href: My_CV/CV_M_Shiroya.pdf
      - icon: github
        href: https://github.com/Mehul0111
        target: _blank
      - text: "{{< fa brands bluesky >}}"
        href: https://bsky.app
        target: _blank
      - icon: rss
        href: posts.xml
        target: _blank

  page-navigation: true

  page-footer:
    left: "[Mehul0111](http://www.github.com) &copy; <script>document.write(new Date().getFullYear())</script>"
    center: ""
    right:
      - icon: github
        href: https://github.com/Mehul0111
        target: _blank
      - text: "{{< fa brands bluesky >}}"
        href: https://bsky.app
        target: _blank
      - icon: rss
        href: posts.xml
        target: _blank

  search:
    location: navbar
    type: textbox

  reader-mode: true
  draft-mode: unlinked

  repo-url: https://github.com/drganghe/quarto-academic-website-template
  open-graph: true
  twitter-card: true
  site-url: "https://drganghe.github.io/quarto-academic-website-template"

  google-analytics:
    tracking-id: ""
    anonymize-ip: true

bibliography: references.bib

format:
  html:
    theme: cosmo
    css:
      - styles.css
      - newstyles.css
    smooth-scroll: true
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'

    # Keep your existing include AND add bootstrap icons
    include-in-header:
      - files/includes/_academic.qmd
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
