
project:
  type: website
  output-dir: docs

description-meta: "Website Mehul"
author-meta: "Dr. Mehulkumar Shiroya"

website:
  title: "Mehulkumar Shiroya"

format:
  html:
    theme: cosmo
    css:
      - styles.css
      - newstyles.css
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
